# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bf7535eed38611de06fa7a0c243f124524b3249d0f92af655be6ad11cff72c2816edac5d16a6c7442c3707b3edc2ec2ce5c0db28c2d84a953d3b7a8d0fda72e

test:
  secret_key_base: 88484805c1cf69c895a29e97bbca2316da389266e96d4aa27fab1a4bde589dd179d36ef01acecb32a4213d0360450ddf2eaa10bf7c35aa1e8cdc87bda4754d40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
